0d3ng/course-daspro-TI1A

attendances/05/23_Muhammad Asadillah Ramadhan.md

Tugas Minggu ke-5 Muhammad Asadillah Ramadhan

Pengumpulan tugas ke-5 Muhammad Asadillah Ramadhan

---

attendances/05/29-Tio Misbaqul Irawan.md

Nama : Tio Misbaqul Irawan
Kelas/No: 1A/29
NIM: 2141720003

Pengumpulan Tugas

---

attendances/05/14_Fikril Hadad Ramadhani.md

Pengumpulan Jobsheet minggu kelima.

kode program dan penjelasan ngebut

---

attendances/05/09_Dhayu Intan.md

Assalamualaikum Pak.. Berikut pengumpulan jobsheet 5; Dhayu Intan Nareswari/09

Pengumpulan jobsheet 5, Dhayu Intan Nareswari/09

---

attendances/05/17-Lailatul Badriyah.md

Assalamualaikum, berikut tugas pemilihan 1 saya. Terima kasih.

Commit Tugas Pemilihan 1

---

attendances/05/20_Muhammad Fikri Ardiansyah.md

Pengumpulan Tugas 5 Muhammad Fikri Ardiansyah

Pengumpulan tugas 5

---

attendances/05/19-Maulana Arif WIjaya.md

tugas saya yang selesai di commit yang pertemuan 5 pak, untuk commit Hallo dan hello itu tadi saya cuma coba coba

Pertemuan 5

---

attendances/05/17-Lailatul Badriyah.md

Assalamualaikum, berikut tugas pemilihan 1 saya.  Terima kasih.

Pembaharuan Tugas Pemilihan 1

---

attendances/05/22-Muhammad Aqilul Muttaqin.md

jobsheet 5 Muhammad Aqilul Muttaqin(22)

jobsheet 5 Muhammad Aqilul Muttaqin(22)

---

attendances/05/11-Diah Putri Nofianti.md

Diah Putri Nofianti/11/2141720054

JOBSHEET 5 PEMILIHAN 1

---

attendances/05/06_Alief Vilza H.md

Pengumpulan Tugas 06_Alief Vilza H_2141720235

Pengumpulan Tugas 06_Alief Vilza H_2141720235

---

attendances/05/17-Lailatul Badriyah.md

Assalamualaikum, berikut tugas pemilihan 1 saya. Terima Kasih. (Lailatul Badriyah - 2141720036)

Update Tugas Pemilihan 1

---

attendances/05/11-Diah Putri Nofianti.md

Menyamakan gambar dengan soal.

JOBSHEET 5 PEMILIHAN 1 (Perbaikan gambar)

---

attendances/05/27_Novita Dwi Rahmadani.md

Novita Dwi Rahmadani 27 jobsheet5

Novita Dwi Rahmadani 27 jobsheet5

---

attendances/05/01_Adinda Kurnia Rifanti_Jobsheet Pemilihan.md

Assalamualaikum Pak, Nama saya Adinda Kurnia Rifanti NIM 2141720100. Mohon izin mengumpulkan tugas Jobsheet Pemiihan 1.

Pengumpulan Tugas Jobsheet Pemilihan 1

---

attendances/05/28-Taufiqy Firdaus Jatu.md

28-Taufiqy Firdaus Jatu

---

attendances/06/29-Tio Misbaqul Irawan.md

Tio Misbaqul Irawan/1A-TI/29/2141720003

Pengumpulan tugas jobsheet 6

---

attendances/06/09_Dhayu Intan Nareswari.md

Assalamualaukum pak.. Saya Dhayu Intan/09 ingin mengumpulkan jobsheet 6.. Terima kasih...

Pengumpulan Jobsheet 6 Dhayu Intan

---

attendances/06/16-Josafat Pratama Susilo .md

Assalamualaikum, Selamat Sore Pak
Saya Josafat Pratama Susilo dari kelas TI 1A D4 ingin mengumpulkan Tugas 6
Terimakasih

Pengumpulan tugas 6 Pemilihan-2

---

attendances/06/22-Muhammad Aqilul Mutaqin.md

praktikumDasPro 6 Muhammad Aqilul Muttaqin(22)

praktikumDasPro 6

---

attendances/06/02_Afif Lukmanul Hakim.md

Pengumpulan Jobsheet 6

---

17-Lailatul Badriyah.md

Assalamualaikum, berikut update tugas jobsheet 6 - pemilihan 2 saya. Terima kasih

Pengumpulan Jobsheet 6 - Pemilihan 2

---

attendances/06/14_FIkrilHadadRamadhani.md

Hari ini saya mengumpulkan jobsheet pada minggu keenam.
terima kasih atas ilmunya pak

pemrograman panas

---

attendances/06/01_Adinda Kurnia Rifanti_Pemilihan2.md

Nama: Adinda Kurnia Rifanti
Kelas/No: TI-1A / 01
NIM: 2141720100

Pengumpulan Jobsheet Pertemuan 6

---

attendances/10/16-Josafat Pratama Susilo.md

Selamat Siang Pak,
Saya Josafat Pratama Susilo, izin mengumpulkan Jobsheet pertemuan ke-10
Terimakasih Pak

Mengumpulkan Jobsheet Pertemuan ke-10

---

attendances/11/16-Josafat Pratama Susilo.md

Selamat Siang Pak,
Saya Josafat Pratama Susilo dari kelas 1A D4 TI ingin mengumpulkan Jobsheet,
Terimakasih.

Mengumpulkan Jobsheet pertemuan ke-11

---

attendances/13/16-Josafat Pratama Susilo.md

Selamat Sore Pak,
Saya Josafat Pratama Susilo ingin mengumpulkan jobsheet pertemuan ke-13,
Terimakasih

Mengumpulkan Jobsheet Pertemuan ke-13

---

attendances/13/02_Afif Lukmanul Hakim.md

02_Afif Lukmanul Hakim pengumpulan tugas jobsheet fungsi

Pengumpulan Jobsheet Fungsi

---

attendances/13/18-M. Rom doni.md

Pengumpulan tugas fungsi

---

attendances/14/16-Josafat Pratama Susilo.md

Selamat Sore Pak, 
Saya Josafat Pratama Susilo ingin mengumpulkan Jobsheet ke-14,
Terimakasih

Pengumpulan Jobsheet ke-14
